bitfinexcom/bfx-report-electron

init.sh, package.json, server.js
This PR adds support of the express server [bfx-report-express](https://github.com/bitfinexcom/bfx-report-express/pull/1) as the  submodule of [bfx-report-ui](https://github.com/bitfinexcom/bfx-report-ui) repository
- This PR depends on those PRs:
https://github.com/bitfinexcom/bfx-report-express/pull/1
https://github.com/bitfinexcom/bfx-report/pull/93
https://github.com/bitfinexcom/bfx-report-ui/pull/210
=> Add support of express server bfx-report-express as submodule of bfx-report-ui repo

helpers/electron-window-state.js, index.js
This PR fixes server initialization which is related to the non-triggering of the electron event `ready-to-show`. If the method `window.maximize()` is called, then `ready-to-show` event does not fire. It worked after the `maximize()` call was removed
https://github.com/electron/electron/issues/7779#issuecomment-463157343
=> Fix server initialization

helpers/index.js, server.js
This PR changes server initialization  for using [bfx-report#136](https://github.com/bitfinexcom/bfx-report/pull/136) and [bfx-report-express#6](https://github.com/bitfinexcom/bfx-report-express/pull/6) with `WebSockets`
**Depends** on these PRs:
- [bfx-report#136](https://github.com/bitfinexcom/bfx-report/pull/136)
- [bfx-report-express#6](https://github.com/bitfinexcom/bfx-report-express/pull/6)
=> Change server initialization

server.js, src/initialize-app.js, src/show-migrations-modal-dialog.js
This PR adds two modal dialogs to show DB migration state when a user import DB:
- DВ migration failed
- DB migration completed
**Depends** on this PR: [bfx-reports-framework#62](https://github.com/bitfinexcom/bfx-reports-framework/pull/62)
=> Add two modal dialogs to show DB migration state

README.md, init.sh, package.json, server.js, src/create-menu.js, src/helpers/index.js, src/helpers/utils.js, src/initialize-app.js, src/run-server.js
This PR fixes launching on mac by double click. Basic changes:
- moves writing files as temporary csv files, logs, dbs of lokue queues, sqlite db to the `app.getPath('userData')` directory https://electronjs.org/docs/all#appgetpathname
- moves writing csv reports in `~/Library/Application Support/bfx-report-electron/csv` (`app.getPath('userData')`) directory for Mac release
- adds an ability to set grape address without overwriting config file
**Depends** on this PR [bfx-reports-framework#71](https://github.com/bitfinexcom/bfx-reports-framework/pull/71)
=> Fix launching on mac by double click issue

package.json, server.js, src/change-reports-folder.js, src/configs-keeper.js, src/const.js, src/create-menu.js, src/errors/index.js, src/export-db.js, src/import-db.js, src/initialize-app.js, src/run-server.js, src/show-error-modal-dialog.js, src/window-creators.js, src/window-state-keeper.js
This PR adds an ability to store users csv path into json config. Basic changes:
- store users csv path into json config
- add ability to change reports folder via the menu bar option `Tools` -> `Change reports folder`
- fix menu bar hotkeys
- set csv folder by default on mac `Documents/BitfinexReports`, on linux and win `csv` folder in the root of the app
- https://github.com/bitfinexcom/bfx-report-electron/pull/39
=>  Add ability to store users csv path into json config

.gitignore, README.md, build/linux-launcher/Bitfinex Report.desktop, build/linux-launcher/Makefile, build/linux-launcher/launcher.c, build/linux-launcher/launcher.sh, build/linux-launcher/msg-box.sh, scripts/init.sh
This PR fixes the electron launcher issue for `Ubuntu 20.X`.
This issue came from updating electron from `v4.0.0` and above. The upstream changed their build process and changed the binary format from `ELF` to `PIE`, related issue https://github.com/electron/electron/issues/15406 
File managers utilize the file command to decide what to do with a file (e.g. open an image viewer, a text editor or execute the file). The file cannot distinguish between shared libraries and PIE executables and therefore misclassifies `PIE` files (see the corresponding [bug report](https://bugs.launchpad.net/ubuntu/+source/file/+bug/1747711)).
In this https://github.com/bitfinexcom/bfx-report-electron/pull/56 PR was decided to apply the solution to use `.desktop` file.
According to a code …
=> Fix the electron launcher issue for Ubuntu 20.X

Dockerfile.linux-builder, Dockerfile.mac-builder, Dockerfile.win-builder, build/linux-launcher/launcher.sh, package.json, scripts/init.sh, scripts/node/make-app-update-yml.js, src/auto-updater/bfx.appimage.updater.js, src/auto-updater/index.js, src/auto-updater/utils.js, src/create-menu.js, src/initialize-app.js
This PR adds the auto-update for Linux, it's the next part of the previous auto-update PR https://github.com/bitfinexcom/bfx-report-electron/pull/82
Basic changes:
- Adds ability to build [AppImage](https://www.electron.build/configuration/appimage) releases
- Adds supporting auto-update for Linux
- Fixes Linux launcher to avoid redundant warning
- Adds the ability to perform auto-update for Linux `ZIP` release
- Fixes missing `bc` cli in docker container
- Fixes `csv` export issue for `AppImage`, forces storing in `~/Documents` dir
- Bumps electron version up to `11.4.2` to fix a crash when exiting app with active nodejs `worker_threads` https://github.com/electron/electron/pull/28471
- Avoids redundant logs
TODO:
- auto-update feature for Mac
=> Add auto-update for linux

scripts/init.sh, server.js, src/auto-updater/index.js, src/initialize-app.js, src/window-creators.js
This PR adds the ability to export csv files by default in the following ways:
- if user uses Mac or AppImage on Linux or NSIS on Windows csv files would be stored in `app.getPath('documents')` + `bitfinex/reports` folder https://www.electronjs.org/docs/api/app#appgetpathname
- if user uses Zip releases (not Mac) csv files would be stored in `csv` folder of the application root
However, the export path can still be specified via the menu item option
Basic changes:
- Changes users export csv folder path
- Don't crash the app when checking for updates is failed
- Hide the main window when the app can't be initialized
- https://github.com/bitfinexcom/bfx-report-electron/pull/85
=> Change users export csv folder path

package.json
This PR fixes supporting node v12.*. The issue is following: the `electron-updater` was updated with adding this
https://github.com/electron-userland/electron-builder/commit/c623279a31d3d203ad1f150d83905a7e1f58a731#diff-9da93fcc7c4be00ef66a6210b155ac689b7f761ec0bfc6a97346e1dfd1d77386R5
```js
import { mkdir, readFile, rename, unlink } from "fs/promises"
```
The error was due to unsupported Node version 12.x which doesn't support this require statement
https://stackoverflow.com/questions/64725249/fs-promises-api-in-typescript-not-compiling-in-javascript-correctly
**Note**: when we take this PR https://github.com/bitfinexcom/bfx-report-electron/pull/90 the hardcode of `electron-updater` might be removed due nodejs would be bumped up
=> Fix supporting node v12

package.json
This PR fixes the [electron-alert](https://github.com/rocketlaunchr/electron-alert) modal dialog. The new `0.1.14` version has been updated to Swal v11 https://github.com/rocketlaunchr/electron-alert/pull/12 and it breaks the codebase. As a solution, need to hardcode `0.1.13`. In the future would add support for `0.1.14` version
=> Fix electron-alert modal dialog

docker-compose.yaml, package.json, scripts/build-ui.sh, scripts/init.sh, src/change-sync-frequency.js, src/error-manager/render-markdown-template.js, src/helpers/get-debug-info.js, src/window-creators.js
This PR adds improvements for dev mode to be able to launch electron without building releases using:
```console
npm run init
or npm run init -d
npm run electron
```
Basic changes:
- Fixes app update config for dev mode
- Fixes ui build for dev mode
- Fixes setting bfx staging url for dev mode
- Fixes eslint config for dev mode
- Adds ability to get `grenache-grape` from github url
- Disables react preflight check when ui is building
- Bumped standard up to 16.*, fixes corresponding code style
- Bumped electron up to `13.1.6` which has important fixes. There are fixed the found issue https://github.com/electron/electron/issues/29732, check https://github.com/electron/electron/pull/29813 and https://github.com/electron/electron/pull/29956
=> Add improvements for dev mode

build/linux-launcher/launcher.sh, package.json, server.js, src/const.js, src/create-menu.js, src/export-db.js, src/import-db.js, src/pause-app.js, src/relaunch.js, src/remove-db.js
This PR adds the ability to clear all tables. Basic changes:
- Adds the option `Clear all data` to the main menu bar
- Bumps electron version up to `13.1.7`
- Allows prereleases to be able to work with auto-update with semantic beta versions like `vX.X.X-beta.X`
- Fixes ability to relaunch app for Linux releases (it uses when auto-update/import/remove-db/clear-all-data) https://github.com/electron-userland/electron-builder/issues/1727#issuecomment-769896927
- Don't show `GtkDialog` warning, related to the electron issue https://github.com/electron/electron/issues/12423
- Fixes `import/export` DB feature - there has to add sqlite WAL file to import/export `.zip`
- https://github.com/bitfinexcom/bfx-reports-framework/pull/179
=> Clear all tables

docs/user-manual.md, package.json, src/create-menu.js, src/errors/index.js, src/modal-dialog-src/modal-dialog.css, src/show-docs/index.js
This PR adds a user manual:
- adds `Markdown` documentation to the electron repository into `docs` folder of the root
- adds an option into the menu bar to open a modal dialog where the user can see the user manual
=> Add user manual

package.json
This PR bumps electron version up to `13.4.0` to have the following fixes:
- https://github.com/electron/electron/releases/tag/v13.2.0
- https://github.com/electron/electron/releases/tag/v13.2.1
- https://github.com/electron/electron/releases/tag/v13.2.2
- https://github.com/electron/electron/releases/tag/v13.2.3
- https://github.com/electron/electron/releases/tag/v13.3.0
- https://github.com/electron/electron/releases/tag/v13.4.0
=> Bump electron version up to 13.4.0

.dockerignore, .gitignore, README.md, dev-app-update.yml, package.json, src/auto-updater/index.js, src/auto-updater/toast-src/toast.css, src/auto-updater/toast-src/toast.js, src/change-sync-frequency.js, src/error-manager/index.js, src/error-manager/show-modal-dialog.js, src/helpers/get-alert-custom-class-obj.js, src/helpers/index.js, src/modal-dialog-src/modal-dialog.css, src/restore-db/index.js, src/show-docs/index.js, src/window-creators.js
This PR allows continuing work with the app when reporting errors. The main changes:
- Bumps `electron-alert` up to `v0.1.20`. The main reason is: the new version of `electron-alert` has bumped the version of [SweetAlert2](https://github.com/sweetalert2/sweetalert2) up to `v11` which has an option to add three buttons to a modal dialog. In this case, the idea is: when an error occurs show three btn `Report`/`Cancel`/`Exit` to provide users the ability to select what should be done, `Cancel` the modal dialog, or `Exit` the app
- Migrate `electron-alert` styles/api to `v0.1.20`
- Adds an option to debug auto-update flow non-packaged build. For this, just need to set the corresponding environment variable before running `npm start`: `export IS_AUTO_UPDATE_BEING_TESTED=true`
- Adds separate …
=> Allow continuing when reporting errors

src/auto-updater/toast-src/toast.css
This PR fixes auto-update toast window styles:
- wrong layout
- would be:
=> Fix auto-update toast window styles

electron-builder-config.js
This PR adds a zipped `AppImage` release of the app to the electron build flow as a simple way to avoid users adding executable permission manually after downloading binary artifact. Also, leaves unzipped `AppImage` release for auto-update
=> Add zipped AppImage release to electron build flow

CHANGELOG.md, package.json
- Added a zipped `AppImage` release of the app to the electron build flow as a simple way to avoid users adding executable permission manually after downloading binary artifact. Also, leaves unzipped `AppImage` release for auto-update. PR: [bfx-report-electron#162](https://github.com/bitfinexcom/bfx-report-electron/pull/162)
- Added `win/loss` vs `previous day balance` results. PR: [bfx-reports-framework#233](https://github.com/bitfinexcom/bfx-reports-framework/pull/233)
- Added one more option to `Select Report Type` selection of the`win/loss` chart: `Percentage Gains (gains/deposits)` and `Percentage Gains (gains/balance)` options. PR: [bfx-report-ui#545](https://github.com/bitfinexcom/bfx-report-ui/pull/545)
- Added `Sum` option to the columns context menu and related logic to show a …
=> Release version 3.8.0 to beta

.github/workflows/build-electron-app.yml
This PR adds ability to make releases using `GitHub Actions` against the BFX API Staging manually. To do this need to set `IS_BFX_API_STAGING` env var https://github.com/bitfinexcom/bfx-report-electron/blob/master/.env.example#L2
=> Add ability to use BFX API Staging via GitHub Actions

CHANGELOG.md, package.json
This PR bumps version up to `v4.2.0`, adds `changelog`
=> Bump version up to v4.2.0

CHANGELOG.md, package.json
- Fixed the `auto-update` issue to turn on by default. The issue is in the parsing of the environment variable `IS_AUTO_UPDATE_DISABLED` from string to boolean. PR: [bfx-report-electron#198](https://github.com/bitfinexcom/bfx-report-electron/pull/198)
=> Release version 4.5.2 to beta

.github/workflows/build-electron-app.yml, Dockerfile.linux-builder, Dockerfile.mac-builder, Dockerfile.ui-builder, Dockerfile.win-builder, package.json, scripts/helpers/install-backend-deps.sh, scripts/helpers/install-nodejs.sh, src/auto-updater/index.js, src/auto-updater/toast-src/toast.js, src/serve.js, src/window-creators.js
This PR bumps electron version up to `v21.3.3` to have nodejs `v16` under the hood to resolve the ability to build UI and electron releases using the same nodejs version
---
Basic changes:
- Bumps electron version up to `v21.3.3`, electron-updater up to `v5.3.0`, electron-builder up to `v23.6.0`
- Bumps nodejs version up to `v16.20.0` for GitHub Actions
- Bumps nodejs version up to `v16.20.0` for Docker containers
- Fixes backend deps installation script
- Fixes ability to serve ui static files
- Fixes auto-update toast width
=> Bump electron version up to 21.3.3

src/trigger-electron-load.js
This PR fixes issue with reloading UI page via the menu bar options. In the electron env need to `trigger-electron-load` event after running `Force Reload` and `Reload` menu commands with express api port
=> Fix issue with reloading ui page via menu bar opts

src/error-manager/github-issue-template.md, src/error-manager/render-markdown-template.js, src/helpers/get-debug-info.js, src/helpers/index.js, src/helpers/is-bfx-api-staging.js, src/window-creators.js
This PR adds a note to the electron app that BFX API Staging is used
---
Basic changes:
- adds a note to the `title` of the app
- adds a note to the `About` modal window
- adds a note to the debug info of the GitHub issue template
Examples of layouts:
=> Add note to app that bfx api staging is used

CHANGELOG.md, package.json
- Fixed issue with passing symbol parameter for `Order Trades` due to the last major changes of the `BFX API` [library](https://github.com/bitfinexcom/bfx-api-node-rest/blob/master/lib/rest2.js#L918). PR: [bfx-report#303](https://github.com/bitfinexcom/bfx-report/pull/303)
- Reverted [(improvements) Reports tables representation](https://github.com/bitfinexcom/bfx-report-ui/pull/664) due to an issue with table scroll. PR: [bfx-report-ui#667](https://github.com/bitfinexcom/bfx-report-ui/pull/667)
=> Release version 4.8.1 to beta

CHANGELOG.md, package.json
- Added `last/first` trades timestamps into the `Weighted Averages` report for the framework mode. PRs: [bfx-report#315](https://github.com/bitfinexcom/bfx-report/pull/315), [bfx-reports-framework#299](https://github.com/bitfinexcom/bfx-reports-framework/pull/299)
- Added `Rate Limit` router to control `BFX API` requests bandwidth to resolve the long timeout issue and help users to go through the data sync. Bumped API call timeout to `90s`. Reduced redundant `positionsAudit` calls to facilitate sync. Fixed stuck event loop to fix `WS` timeout on big data. PRs: [bfx-report#314](https://github.com/bitfinexcom/bfx-report/pull/314), [bfx-reports-framework#298](https://github.com/bitfinexcom/bfx-reports-framework/pull/298)
=> Release version 4.9.1 to beta

CHANGELOG.md, package.json
- Added `last/first` trades timestamps into the `Weighted Averages` report for the framework mode. PRs: [bfx-report#315](https://github.com/bitfinexcom/bfx-report/pull/315), [bfx-reports-framework#299](https://github.com/bitfinexcom/bfx-reports-framework/pull/299)
- Added `Rate Limit` router to control `BFX API` requests bandwidth to resolve the long timeout issue and help users to go through the data sync. Bumped API call timeout to `90s`. Reduced redundant `positionsAudit` calls to facilitate sync. Fixed stuck event loop to fix `WS` timeout on big data. PRs: [bfx-report#314](https://github.com/bitfinexcom/bfx-report/pull/314), [bfx-reports-framework#298](https://github.com/bitfinexcom/bfx-reports-framework/pull/298)
=> Release version 4.9.1

src/auto-updater/index.js, src/change-sync-frequency.js, src/error-manager/show-modal-dialog.js, src/restore-db/index.js, src/show-docs/index.js, src/window-event-manager/index.js
This PR fixes the https://github.com/bitfinexcom/bfx-report-electron/issues/215 related to `MaxListenersExceededWarning` warning for the electron windows
---
Basic changes:
- Adds manager for `closed` window event being `once` bubbled, for better handling
- Fixes download progress showing for the auto-update in cases when the event happens faster than the `alert` fires
=> Fix max listeners exceeded warning

CHANGELOG.md, package.json
- Removed the `Cumulative Weighted Price` column and corresponding logic from the `Weighted Averages` report according to the latest requirements. Added `Cost` and `Sale` columns to the `Weighted Averages` report. PRs: [bfx-report#319](https://github.com/bitfinexcom/bfx-report/pull/319), [bfx-reports-framework#302](https://github.com/bitfinexcom/bfx-reports-framework/pull/302), [bfx-report-ui#681](https://github.com/bitfinexcom/bfx-report-ui/pull/681)
- Improved sync time estimation flow as follows: in addition to existing emitting `WS` events when the next collection is syncing to not hold the previous time value (some collections can sync very long) adds an ability to emit the `progress` event every `1sec` with new values `spentTime` and `leftTime` for better UX (so that the user does …
=> Release version 4.9.2 to beta

CHANGELOG.md, package.json
- Fixed `start` timestamp of `BFX API` queries to be at least `Date.UTC(2013)` = `1356998400000` ms. The issue is the following: some restrictions of the `BFX API` are changed for the `Funding Credits History`, if we set `start: 0` throws `Internal Server Error` from the `API` side. It's an issue for the `sync` mode (as we start syncing with `0`) and setting the default value for requests. PRs: [bfx-report#324](https://github.com/bitfinexcom/bfx-report/pull/324), [bfx-reports-framework#307](https://github.com/bitfinexcom/bfx-reports-framework/pull/307)
=> Release version 4.9.3 to beta

server.js
This PR provides `10min` express server timeouts for complicated reports which can have a lot of internal calls to the `BFX API` that can take significant time
---
- https://github.com/bitfinexcom/bfx-report-express/pull/31
=> Provide 10min express server timeouts

src/error-manager/index.js
This PR prevents showing error modal dialog due to inet issue
---
When the sync starts we send a ping request to bfx api to check that api is available
https://github.com/bitfinexcom/bfx-reports-framework/blob/master/workers/loc.api/sync/index.js#L127
https://github.com/bitfinexcom/bfx-reports-framework/blob/master/workers/loc.api/service.report.framework.js#L258
The idea is to not show error modal dialog for issues, just show error toast via UI when fetching the corresponding error with progress event via WS
---
- https://github.com/bitfinexcom/bfx-reports-framework/pull/317
=> Prevent showing error modal dialog due to inet issue

CHANGELOG.md, package.json
- Added ability to show success dialog for `CSV` exporting only after the `emitCsvGenerationCompletedToOne` event was sent by the backend for better understanding by users when the exporting process actually completed. PR: [bfx-report-ui#698](https://github.com/bitfinexcom/bfx-report-ui/pull/698)
- Added the possibility of tweaking the ability to auto-start sync after the auto-update of the electron app via the `Preferences` menu: `shouldNotSyncOnStartupAfterUpdate` flag received on sign in. PR: [bfx-report-ui#699](https://github.com/bitfinexcom/bfx-report-ui/pull/699)
- Implemented [extra information](https://docs.bitfinex.com/reference/movement-info) handling and representation for the `Movements` report. PR: [bfx-report-ui#702](https://github.com/bitfinexcom/bfx-report-ui/pull/702)
- …
=> Release version 4.11.0 to staging

package.json, server.js, src/configs-keeper.js, src/helpers/__test__/ports.spec.js
This PR adds ability to use [lib-js-util-base](https://github.com/bitfinexcom/lib-js-util-base) lib instead of the `lodash`
---
Base changes:
- uses `lib-js-util-base` lib instead of `lodash`
- removes `lodash.isObject` usage as redundant and not used anywhere
=> Use lib-js-util-base instead of lodash

CHANGELOG.md, package.json
- Added ability to inform user that the `platform` is marked in the `maintenance` mode by `WebSocket`. PRs: [bfx-report#331](https://github.com/bitfinexcom/bfx-report/pull/331), [bfx-reports-framework#321](https://github.com/bitfinexcom/bfx-reports-framework/pull/321), [bfx-api-mock-srv#56](https://github.com/bitfinexcom/bfx-api-mock-srv/pull/56)
- Added `Vietnamese` language. PRs: [bfx-report-ui#711](https://github.com/bitfinexcom/bfx-report-ui/pull/711), [bfx-report-ui#712](https://github.com/bitfinexcom/bfx-report-ui/pull/712)
- Actualized synchronization progress handling flow according to the latest backend updates. PR: [bfx-report-ui#710](https://github.com/bitfinexcom/bfx-report-ui/pull/710)
- Fixed `MaxListenersExceededWarning` for complicated csv reports using the `transform` csv …
=> Release version 4.12.0 to staging

CHANGELOG.md, package.json
- Added `test` runner and `HTML report` maker workflows to the GitHub Actions which launch after creating PRs against the `master` branch. PRs: [bfx-report#337](https://github.com/bitfinexcom/bfx-report/pull/337), [bfx-reports-framework#325](https://github.com/bitfinexcom/bfx-reports-framework/pull/325), [bfx-report-electron#259](https://github.com/bitfinexcom/bfx-report-electron/pull/259)
- Implemented `Account Fees`, `Account Value` and `LEO level` sections on the new `Summary` page, added minor styling adjustments. PR: [bfx-report-ui#716](https://github.com/bitfinexcom/bfx-report-ui/pull/716)
- Removed `lodash` lib usage. PRs: [bfx-report#336](https://github.com/bitfinexcom/bfx-report/pull/336), [bfx-report-ui#717](https://github.com/bitfinexcom/bfx-report-ui/pull/717), …
=> Release version 4.13.0 to staging

.github/dependabot.yml
This PR sets the [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) against the `stagin` branch to not trigger test-runner workflow
=> Set dependabot against staging branch

src/error-manager/index.js
This PR prevents throwing an error when GitHub server can't respond to the auto-update requests
---
Fix for these issues:
- https://github.com/bitfinexcom/bfx-report-electron/issues/239
- https://github.com/bitfinexcom/bfx-report-electron/issues/264
---
- https://github.com/bitfinexcom/bfx-report-electron/pull/263
=> Prevent throwing error when GitHub server can't respond to auto-update requests

CHANGELOG.md, package.json
- Added `Summary by Asset` section for the last 30 days on the new `Summary` for the `Reports` app. Added refreshing for all `Summary` sections on the `Filter` button click. PR: [bfx-report-ui#726](https://github.com/bitfinexcom/bfx-report-ui/pull/726)
- Added ability to sync daily `candles` once per day to reduce the number of sync requests to `BFX API` and as a result improve the situation with the `Rate Limit` restriction. PR: [bfx-reports-framework#334](https://github.com/bitfinexcom/bfx-reports-framework/pull/334)
- Added ability to reference specific user currencies when `candles` sync. The aim is to reduce the amount of requests to the `BFX API` candles endpoint and speed up the sync essentially. Also for better UX, added approximate candles sync time estimation considering the …
=> Release version 4.15.0 to staging

CHANGELOG.md, package.json
- Added the `start` param to the `Summary by Asset` to be able to select a period more than `30d`. PR: [bfx-reports-framework#342](https://github.com/bitfinexcom/bfx-reports-framework/pull/342)
- Added exchange volume and trading fee values to the the `Summary by Asset`. PR: [bfx-reports-framework/pull/344](https://github.com/bitfinexcom/bfx-reports-framework/pull/344)
- Added exceptions for the error modal window. It should cover the follow cases: `database is locked` and `network timeout`. PR: [bfx-report-electron#285](https://github.com/bitfinexcom/bfx-report-electron/pull/285)
- Implemented `ETH2P (ETH2Pending)`, `ETH2R (ETH2Rewards)` and `ETH2U (ETH2Unstaking)` availability in the `Symbol` selector. PR: [bfx-report-ui#740](https://github.com/bitfinexcom/bfx-report-ui/pull/740)
- …
=> Release version 4.16.0 to staging

package.json, scripts/node/generate-mac-zipand-blockmap.js, src/auto-updater/index.js, src/manage-worker-messages.js, src/window-creators.js
This PR resolves `dependabot` dependency updates:
- https://github.com/bitfinexcom/bfx-report-electron/pull/269
- https://github.com/bitfinexcom/bfx-report-electron/pull/270
- https://github.com/bitfinexcom/bfx-report-electron/pull/272
- https://github.com/bitfinexcom/bfx-report-electron/pull/273
- https://github.com/bitfinexcom/bfx-report-electron/pull/280
---
Basic changes:
- Bump `app-builder-bin` up to 4.2.0 https://github.com/develar/app-builder/commits/v4.2.0
- Fix execute permission for `app-builder-bin`. Binary does not have an execute permission by default: https://github.com/develar/app-builder/issues/97
- Bump `standard` up to 17.1.0
- Fix code style considering standardjs 17
- Bump `electron` up to 27.2.0 https://releases.electronjs.org/release/compare/v27.0.4/v27.2.0
- Bump …
=> Resolve dependabot dependency updates

electron-builder-config.js
This PR fixes skipping publishing of artifact for `Mac` by `electron-builder`
The issue came from this PR of `electron-builder`: https://github.com/electron-userland/electron-builder/pull/7715
---
The build logs with issue:
```console
mac-builder    | Mac release has been zipped successfully
mac-builder    |   • skipping publish of artifact, already published  newArtifact=/project/dist/BitfinexReport-4.17.0-beta.3-x64-mac.zip
```
=> Fix skipping publishing of artifact for mac by electron-builder

CHANGELOG.md, package.json
- Added ability to define what kind of API keys are stored `prod`/`staging`. The `prod`/`staging` is detected by existing the `staging` string in the restUrl config option: `https://api-pub.bitfinex.com`/`https://api.staging.bitfinex.com`. And `isStagingBfxApi` flag is set or updated on `signUp`/`signIn` to the `user` table. Than, `getUsers` endpoint will return the `isStagingBfxApi` flag to be shown in the UI for each user on the login stage. PR: [bfx-reports-framework#347](https://github.com/bitfinexcom/bfx-reports-framework/pull/347)
- Added automated testing for electron app binaries. The flow: build release on GitHub Actions, use unpacked builds for E2E tests, launch E2E test on Linux and Mac and Win OSs independently, provide E2E test reports for every OS launch. PR: …
=> Release version 4.17.0 to staging

CHANGELOG.md, package.json
- Added ability to close the drawer on mobile when clicking on a item of the menu. PR: [bfx-report-ui#764](https://github.com/bitfinexcom/bfx-report-ui/pull/764)
- Added environment configuration during the `Google Tag Manager` initialization. PR: [bfx-report-ui#767](https://github.com/bitfinexcom/bfx-report-ui/pull/767)
- Added an option to skip `Mac` build notarizing and signing when running manually. PR: [bfx-report-electron#314](https://github.com/bitfinexcom/bfx-report-electron/pull/314)
- Enhanced representation of the app `Summary` sections loading states according to the latest design updates. Added showing loading states for them during initial sync. PR: [bfx-report-ui#768](https://github.com/bitfinexcom/bfx-report-ui/pull/768)
=> Release version 4.19.0 to staging

.dockerignore, electron-builder-config.js, server.js, src/change-reports-folder.js, src/const.js, src/errors/index.js, src/initialize-app.js, src/print-to-pdf/index.js, src/run-server.js
This PR adds support for `PDF` reports
---
Basic changes:
- the minimum required refactoring in order to be able to add support for pdf to the current csv generation flow
- adds logic to be able to generate PDF under `Electronjs` using the native api of `Chromium` https://www.electronjs.org/docs/latest/api/web-contents#contentsprinttopdfoptions
---
How PDF generation works
For PDF generation uses browser emulation with printing HTML to PDF format:
- under Electronjs uses the internal api which used via the IPC (between framework child process and main electronjs process) with the newest browser emulation `Chromium` https://www.electronjs.org/docs/latest/api/web-contents#contentsprinttopdfoptions
Feature has the following flow:
- `PUG` templates which provide flexibility with inheritance …
=> Add support for PDF reports

.env.example, .github/workflows/build-electron-app.yml, .github/workflows/e2e-test-report.yml, .github/workflows/test-report.yml, Dockerfile.linux-builder, Dockerfile.mac-builder, Dockerfile.ui-builder, Dockerfile.win-builder, docker-compose.yaml, electron-builder-config.js, electronEnv.json.example
This PR optimizes GitHub Actions Workflow for release build
---
Basic changes:
- Prevents `electron-builder` config modifying when setting repo owner in GH Actions Workflow, adds ability to set repo owner from env var into electron-builder config. It's more secure and flexible for beta releases as well
- Skips GH Actions Workflow for tests report if the test runner is canceled
- Launchs GH Actions Workflow for E2E tests when the build is successful
- Fixes random failed to install npm package from git in Docker. Related to this issue: https://github.com/npm/cli/issues/624
=> Optimize GitHub workflow for release build

.github/workflows/build-electron-app.yml, .github/workflows/ci.yml, scripts/build-release.sh, scripts/setup.sh
This PR updates GH Actions to use Nodejs `v20`
---
Context: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
Our current warnings: https://github.com/bitfinexcom/bfx-report-electron/actions/runs/7913595670
---
Basic changes:
- Update gh actions to resolve deprecation warnings
- Point `coactions/setup-xvfb` gh action to exact commit to have required nodejs ver under hood: resolved here https://github.com/coactions/setup-xvfb/pull/23
- Fix disabling auto-update when build release. Minore improvement for `beta` releases
---
TODO:
- GH Action `dorny/test-reporter` does not still support `actions/upload-artifact@v4` required for Nodejs 20 migration. And to upload `test reports` needs to use `v3` with Nodejs v16 which will show one related warning …
=> Update actions to use Nodejs v20

.github/workflows/build-electron-app.yml
This PR adds option to set repo owner for auto-update in manual run
---
=> Add option to set repo owner for auto-update in manual run

package.json, src/error-manager/index.js, src/print-to-pdf/index.js
This PR improves print pdf under electron
---
Basic changes:
- Turn off ipc log transport between render and main process as unused, it prevents ipc transport error from `electron-log` lib like:
```console
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
at WebFrameMain.send (node:electron/js2c/browser_init:2:93682)
at WebContents.send (node:electron/js2c/browser_init:2:79161)
at /home/vladimir/projects/bitfinex/bfx-report-electron/node_modules/electron-log/src/electronApi.js:205:23
at Array.forEach (<anonymous>)
at sendIpcToRenderer (/home/vladimir/projects/bitfinex/bfx-report-electron/node_modules/electron-log/src/electronApi.js:203:42)
at Object.sendIpc (/home/vladimir/projects/bitfinex/bfx-report-electron/node_modules/electron-log …
```
=> Improve print pdf under electron

.github/workflows/build-electron-app.yml, .github/workflows/ci.yml, .github/workflows/e2e-test-report.yml, .github/workflows/test-report.yml
This PR adds the last part of the previous https://github.com/bitfinexcom/bfx-report-electron/pull/323 updates GH Actions to use Nodejs v20
---
Context: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
Our current warnings: https://github.com/bitfinexcom/bfx-report-electron/actions/runs/8169998113
---
Solution:
- as `dorny/test-reporter` GH Action is stuck with the update to support actions/upload-artifact@v4
- turns off downloading test results managed `dorny/test-reporter` with removing `artifact` options
- adds additional downloading step before `dorny/test-reporter` using `actions/download-artifact@v4` actions
- and after all, we can use `actions/upload-artifact@v4` everywhere
---
**Notes:**
- after opening PR against `master` the unit …
=> Update gh actions to use nodejs v20

.github/workflows/build-electron-app.yml, scripts/build-release.sh
This PR adds ability to upload a dist release if the repo owner is customized
---
The idea is the following:
- have the ability to set custom repo owner for auto-update
- it's useful for `beta` and `main` releases made against the `forked` repo
- as the `electron-builder` does not support separate customization of repo owner for publishing and auto-update
- if the custom repo owner is set
- and its set value is different from the current actual repo owner
- turn off the publishing feature of the `electron-builder` functionality
- and then use `actions/upload-artifact@v4` after being built to upload binaries to the `Artifacts` section of the `Build release` workflow like shown here https://github.com/ZIMkaRU/bfx-report-electron/actions/runs/8276698230
=> Add ability to upload dist release if repo owner is customized

CHANGELOG.md, package.json
- Implemented dynamic width support for the `Reports` tables according to: the tables should stretch and fill horizontally (width 100%). PR: [bfx-report-ui#794](https://github.com/bitfinexcom/bfx-report-ui/pull/794)
- Added `DMG` Mac dist release uploading in case of manual build on a fork. Related to this issue: [bfx-report-electron#352](https://github.com/bitfinexcom/bfx-report-electron/issues/352). PR: [bfx-report-electron#357](https://github.com/bitfinexcom/bfx-report-electron/pull/357)
- Added handling unexpected BFX API errors, added `3` retries with a timeout `10sec` if catches any unexpected errors during report generation or DB sync in framework mode. Related to these issues: [bfx-report-electron#354](https://github.com/bitfinexcom/bfx-report-electron/issues/354), …
=> Release version 4.22.0 to staging

.github/workflows/build-electron-app.yml, CHANGELOG.md, package.json
- Implemented `isStagingBfxApi` flag handling and shows `Staging` prefix for the corresponding keys stored in the DB to improve the manual testing process convenience. PR: [bfx-report-ui#800](https://github.com/bitfinexcom/bfx-report-ui/pull/800)
- Implemented the possibility of manually adjusting columns width and persisting these between sessions. Added the ability to set the auto-calculated dynamic defaults via the context menu. Improved charts responsiveness. PR: [bfx-report-ui#805](https://github.com/bitfinexcom/bfx-report-ui/pull/805)
- Updated `GH Actions` `setup-node` to `v4` to prevent breaking changes in workflow. PRs: [bfx-facs-db-better-sqlite#10](https://github.com/bitfinexcom/bfx-facs-db-better-sqlite/pull/10), [bfx-report#365](https://github.com/bitfinexcom/bfx-report/pull/3 …
=> Release version 4.23.0

CHANGELOG.md, package.json
- Added transaction tax report. PRs: [bfx-reports-framework#373](https://github.com/bitfinexcom/bfx-reports-framework/pull/373), [bfx-reports-framework#378](https://github.com/bitfinexcom/bfx-reports-framework/pull/378), [bfx-reports-framework#379](https://github.com/bitfinexcom/bfx-reports-framework/pull/379), [bfx-reports-framework#380](https://github.com/bitfinexcom/bfx-reports-framework/pull/380), [bfx-reports-framework#381](https://github.com/bitfinexcom/bfx-reports-framework/pull/381), [bfx-reports-framework#382](https://github.com/bitfinexcom/bfx-reports-framework/pull/382), [bfx-reports-framework#383](https://github.com/bitfinexcom/bfx-reports-framework/pull/383), [bfx-reports-framework#384](https://github.com/bitfinexcom/bfx-reports-framework/pull/384), …
=> Release version 4.25.0 to staging

src/manage-worker-messages.js
This PR adds ability to show native notifications in case another screen is displayed and the app window is not hidden with multiple workspaces mode in Ubuntu/Mac
=> Show native notifications with multiple workspaces mode in Ubuntu/Mac

server.js, src/helpers/manage-window.js, src/manage-worker-messages.js, src/show-notification/show-sync-notification.js, src/show-notification/show-trx-tax-report-notification.js
This PR adds ability to show the native notification in the electron app in case the sync is being processed in the background with the hidden main window
There we check if the main window is invisible and show a notification otherwise don't
---
Example:
=> Show native notification for sync if processing with hidden main window

CHANGELOG.md, README.md, package.json
- Added ability to send `IPC` messages when the sync is ready. PR: [bfx-reports-framework#405](https://github.com/bitfinexcom/bfx-reports-framework/pull/405)
- Added ability to show native notifications in case another screen is displayed and the app window is not hidden with multiple workspaces mode in `Ubuntu`/`Mac`. PR: [bfx-report-electron#389](https://github.com/bitfinexcom/bfx-report-electron/pull/389)
- Added ability to show the native notification in the electron app in case the `sync` is being processed in the background with the hidden main window. There we check if the main window is invisible and show a notification otherwise don't. PR: [bfx-report-electron#390](https://github.com/bitfinexcom/bfx-report-electron/pull/390)
- Enhanced and unified `Logins` and `Change Logs` …
=> Release version 4.26.0 to staging

CHANGELOG.md, README.md, package.json, src/error-manager/index.js
- Implemented dynamic height calculation for the `Concentration Risk` pie chart to prevent overflow issues possibility spotted in some cases. PR: [bfx-report-ui#859](https://github.com/bitfinexcom/bfx-report-ui/pull/859)
- Implemented `Last Sync time` handling and representation (approximately in hours) for the `Reports`. PR: [bfx-report-ui#863](https://github.com/bitfinexcom/bfx-report-ui/pull/863)
- Implemented `Profits` section (port of the `Win/Loss` chart with several predefined parameters) on the app `Summary` page. Removed charts smoothness for better precision. PR: [bfx-report-ui#864](https://github.com/bitfinexcom/bfx-report-ui/pull/864)
- Added logic to have separated translations by language in `JSON` files using `i18next` lib for easier translation maintenance. PRs: …
=> Release version 4.28.0

.github/workflows/build-electron-app.yml, package.json, scripts/helpers/install-backend-deps.sh
This PR updates `macOS` on GH Actions from `12` to `15` due to caught warning on the last release:
- https://github.com/bitfinexcom/bfx-report-electron/actions/runs/11010191592
---
Another issue here after updating macOS to `15` is a failure on `ed25519-supercop` dependency binary building:
- https://github.com/ZIMkaRU/bfx-report-electron/actions/runs/11157362245/job/31011500800
And as we removed `ed25519-supercop` from `grenache-grape` https://github.com/bitfinexcom/grenache-grape/commit/f6715d6cdd6cc3ff9cd476538aab8301bc809b3e we can drop integration steps from electron app build flow
It was built and tested on GH Actions:
- https://github.com/ZIMkaRU/bfx-report-electron/releases/tag/v4.29.0-beta.1
- https://github.com/ZIMkaRU/bfx-report-electron/actions/runs/11158307513
- …
=> Update macOS on GH Actions

electron-builder-config.js
This PR fixes `dotenv` importing for prod env
---
We use `dotenv` in `electron-builder` config file to build binaries and this dependency is in the dev section. It needs to exclude importing `dotenv` under prod env as we use that config file in the main code (not only for assembly), but `dotenv` is redundant here
=> Fix dotenv importing for prod env

scripts/helpers/install-nodejs.sh
This PR fixes Docker container preparation for release building
---
The nodejs installation script began to throw an error after `npm cache clear`. In this case, we can omit the error
=> Fix docker container preparation for release building

CHANGELOG.md, package.json
- Implemented `Active Positions` section on the app `Summary` page. PR: [bfx-report-ui#873](https://github.com/bitfinexcom/bfx-report-ui/pull/873)
- Added `Active Positions` section to the web `Account Summary` page. PR: [bfx-report-ui#874](https://github.com/bitfinexcom/bfx-report-ui/pull/874)
- Improved `fallback` languages for i18next https://www.i18next.com/principles/fallback. PR: [bfx-report#406](https://github.com/bitfinexcom/bfx-report/pull/406)
- Added translation flow to electronjs wrapper. PR: [bfx-report-electron#412](https://github.com/bitfinexcom/bfx-report-electron/pull/412)
- Reworked `ColumnsSelectDialog` in a more performant way and improved props linting. PR: [bfx-report-ui#868](https://github.com/bitfinexcom/bfx-report-ui/pull/868)
- Moved `Account Fees` below other …
=> Release version 4.29.0 to staging

build/locales/en/translations.json, build/locales/ru/translations.json, src/error-manager/collect-logs.js, src/error-manager/show-modal-dialog.js, src/helpers/get-user-data-path.js, src/helpers/index.js, src/initialize-app.js, src/window-creators/index.js, src/window-creators/layouts/app-init-error.html, src/window-creators/main-renderer-ipc-bridge/general-ipc-channel-handlers.js, src/window-creators/main-renderer-ipc-bridge/preload.js, src/window-creators/main-renderer-ipc-bridge/translation-ipc-channel-handlers.js
This PR extends electron app wrapper translations, it's a part of the common task and here improves the app init error layout
---
Basic changes:
- Fix logs collection for bug report
- Improve app init to use translations in error layout
- Add ability to use translations in browser windows
- Add translations for app init error layout
- Use translations in app init error layout
- Fix `zenity` closing behavior for error modal win on `Ubuntu`. The context is if push close button in menu bar `zenity` will exit with `1` which will cause an error
- Add ability to use `app.exit()` method in the browser window of app init error layout
- Improve app init error layout
---
Example of the app init error layout:
=> Extend electron app wrapper translations

package.json, src/initialize-app.js, src/window-creators/change-loading-win-visibility-state.js, src/window-creators/index.js, src/window-creators/layouts/app-init.html, src/window-creators/main-renderer-ipc-bridge/general-ipc-channel-handlers.js, src/window-creators/main-renderer-ipc-bridge/ipc.channel.handlers.js, src/window-creators/main-renderer-ipc-bridge/preload.js, src/window-creators/main-renderer-ipc-bridge/translation-ipc-channel-handlers.js
This PR Improves the app-init layout launch flow
---
Basic changes:
- Adds ability to send/listen events for the app-init layout via the context bridge between the main and renderer ipc to be secure (the same approach as for other layouts)
- Improves the loading window workflow to bring more consistency in the sequence of showing windows. Fixes issue with focusing the main window on the launch
- Bumps `electron` version from `27.3.5` to `27.3.11` to have the latest patch
=> Improve app init layout launch flow

src/i18next/index.js
This PR prevents returning the translation key `key.nestedKey.etc` if a value is missing for a certain language and adds the ability to try to take one from the default `en` translation file
=> Prevent returning translation key if a value is missing

.github/workflows/build-electron-app.yml, scripts/build-release.sh, scripts/build-ui.sh, scripts/setup.sh
This PR improves `bash` scripts to add `macos` compatibility to `sed` cli usage
---
The main changes are to rework `sed` commands to be able to run bash scripts on both OSs Ubuntu and MacOS as they have slightly different implementation
=> Add macos compatibility to sed cli usage

build/locales/en/translations.json, build/locales/ru/translations.json, src/helpers/get-ui-fonts-as-css-string.js, src/helpers/index.js, src/manage-worker-messages.js, src/restore-db/index.js
This PR adds translation support to the `restore-db`. And fixes loading ui fonts to `restore-db` modal window, fixes min-width for restore-db modal window
---
=> Add translation support to restore db

build/locales/en/translations.json, build/locales/ru/translations.json, src/auto-updater/index.js
This PR extends translations for the `auto-update` module buttons and also fixes the width for long text translations
---
Before:
After:
=> Extend translations for auto-update buttons

build/locales/en/translations.json, build/locales/ru/translations.json, src/export-db.js, src/show-error-modal-dialog.js, src/show-message-modal-dialog.js
This PR adds translation support to the `export-db` module
---
=> Add translation support to export-db module

build/locales/en/translations.json, build/locales/ru/translations.json, package.json, src/archiver.js, src/export-db.js, src/show-error-modal-dialog.js, src/window-creators/change-loading-win-visibility-state.js
This PR adds `progress` perc to the loading window for the `export db` module as it can take significant time for large DB
---
The `archiver` lib has a `progress` event available: https://www.archiverjs.com/docs/archiver#event-progress
But this event emits once for each file processed
As we can have large DB files it won't be useful and informative
And to show users that the process is going well adds showing creating archive bytes size, the size refreshes every `3sec`
---
- `en`:
- `ru`:
=> Add progress perc to loading window for export-db module

build/locales/en/translations.json, build/locales/ru/translations.json, package.json, src/archiver.js, src/import-db.js, src/pause-app.js
This PR adds `progress` perc to the loading window for the `import-db` module as it can take significant time for large DB
---
There is no `progress` event available in the `yauzl` lib
We have to handle progress by getting data chunk length for each file stream
---
- en:
- ru:
=> Add progress perc to loading win for import-db module

build/locales/en/translations.json, build/locales/ru/translations.json, src/manage-worker-messages.js, src/remove-db.js
This PR adds translation support to the `remove-db` module
---
- en:
- ru:
=> Add translation support to remove-db module

build/locales/en/translations.json, build/locales/ru/translations.json, src/manage-worker-messages.js, src/show-message-modal-dialog.js
This PR adds translation support to the `manage-worker-messages` module
---
Basic changes:
- Adds translation support to `backup-db`
- Add translation support to `migration-db`
- Fixes showing modal dialogs in sequence
---
- `en`:
- `ru`:
=> Add translation support to manage-worker-messages module

build/locales/en/translations.json, build/locales/ru/translations.json, src/manage-worker-messages.js, src/show-about-modal-dialog.js, src/show-message-modal-dialog.js
This PR adds translation support to the `show-about-modal-dialog` module
---
- `en`:
- `ru`:
---
- https://github.com/bitfinexcom/bfx-report-electron/pull/456
=> Add translation support to show-about-modal-dialog module

Dockerfile.linux-builder, Dockerfile.mac-builder, Dockerfile.ui-builder, Dockerfile.win-builder
This PR fixes docker desktop container user permissions breaks
Fixes chown: `changing ownership of 'path-to-file': Operation not permitted` when using it in `dockerfile`
The context here:
- https://github.com/docker/desktop-linux/issues/252#issuecomment-2436547195
- https://github.com/docker/desktop-linux/issues/9
---
---
The workflow has been tested:
- https://github.com/ZIMkaRU/bfx-report-electron/actions/runs/12006345135
- https://github.com/ZIMkaRU/bfx-report-electron/releases/tag/v4.31.0-beta.2
=> Fix docker desktop container user permissions breaks

build/locales/en/translations.json, build/locales/ru/translations.json, src/auto-updater/index.js, src/change-reports-folder.js, src/change-sync-frequency.js, src/enforce-macos-app-location.js, src/error-manager/get-error-description.js, src/error-manager/index.js, src/error-manager/show-modal-dialog.js, src/export-db.js, src/import-db.js, src/manage-worker-messages.js, src/print-to-pdf/index.js, src/remove-db.js, src/restore-db/index.js, src/show-about-modal-dialog.js, src/show-docs/index.js, src/show-error-modal-dialog.js, src/show-message-modal-dialog.js, src/show-notification/index.js, src/show-notification/show-sync-notification.js, src/show-notification/show-trx-tax-report-notification.js, src/window-creators/layouts/app-init-error.html
This PR optimizes electron translation file data structure to prevent some common duplication and redundant nesting for easier support
=> Optimize electron translation file data structure

src/auto-updater/toast-src/toast.css, src/helpers/get-ui-fonts-as-css-string.js, src/modal-dialog-src/modal-dialog.css, src/window-creators/layouts/app-init-error.html, src/window-creators/layouts/app-init.html
This PR changes the font family from `Roboto` to `Inter` to prevent throwing error due to the last UI changes (electron layouts use font source from the UI sub-module)
---
- https://github.com/bitfinexcom/bfx-report-ui/pull/896
=> Change layout font family to prevent throwing error

src/initialize-app.js
This PR increases app initialization timeout to `30min` to be able to execute sqlite `vacuum` command on launch
---
- https://github.com/bitfinexcom/bfx-report-electron/pull/514
=> Increase app initialization timeout

CHANGELOG.md, package-lock.json, package.json
- Added `package-lock` file, bumped dev dependencies and bumped up `NODEJS` to `v20` for the `GH Actions`. PR: [bfx-facs-db-better-sqlite#12](https://github.com/bitfinexcom/bfx-facs-db-better-sqlite/pull/12)
- Implemented user notifications about inaccurate `Tax Report` calculations due to `delisted` tokens. PR: [bfx-report-ui#926](https://github.com/bitfinexcom/bfx-report-ui/pull/926)
- Implemented the possibility to `Deduct Fees` in the `Tax Report`. PR: [bfx-report-ui#928](https://github.com/bitfinexcom/bfx-report-ui/pull/928)
- Made two loading windows for a startup without a parent window independently and for common purposes as a modal window with a parent window to prevent the main window interaction when showing the loading window for some sensitive cases such as import/export DB. …
=> Release version 4.36.0 to staging

.npmrc, CHANGELOG.md, package-lock.json, package.json
- Added `Summary Statistics` info into the `getSummaryByAsset` endpoint. PR: [bfx-reports-framework#485](https://github.com/bitfinexcom/bfx-reports-framework/pull/485)
- Implemented the possibility to login via `__bfx_token` cookie from the main platform for the `Reports` web in production. PR: [bfx-report-ui#968](https://github.com/bitfinexcom/bfx-report-ui/pull/968)
- Implemented auto-refreshing possibility for the currently opened report after the regular/scheduled synchronization for represented data actualization. PR: [bfx-report-ui#969](https://github.com/bitfinexcom/bfx-report-ui/pull/969)
- Disabled `Account Balance` refresh button during initial synchronization to prevent report generation errors possibility. PR: [bfx-report-ui#967](https://github.com/bitfinexcom/bfx-report-ui/pul …
=> Release version 4.38.0
