bitfinexcom/bfx-report-electron

package.json

pump a version + update sub modules tags

pump a version + update sub modules tags

---

package.json

This PR adds `hardenedRuntime` option to mac config

Add hardened runtime to mac config

---

README.md

Add macOs issue to readme

---

index.js
init.sh
server.js

This PR improves initialization application, adds development menu items

Improve initialization

---

.npmrc
init.sh
package.json
reinstall-deps.sh
src/initialize-app.js

This PR fixes app initializing, the main changes:
- cleanups dev deps
- bumps up electron-builder ver to 21.2.0
- improves init bash script
**Depends** on this PR: [bfx-reports-framework#65](https://github.com/bitfinexcom/bfx-reports-framework/pull/65)

Fix app initializing

---

build-ui.sh
package.json
server.js
src/const.js
src/create-menu.js
src/errors/index.js
src/export-db.js
src/helpers/index.js
src/helpers/utils.js
src/import-db.js
src/initialize-app.js
src/make-or-read-secret-key.js
src/remove-db.js
src/run-server.js
src/show-error-modal-dialog.js
src/window-creators.js

This PR adds support for a new auth way. Basic changes:
- adds an ability to generate a secret key on the first launch to provide into env variable of the reports framework
- adds remove db feature into the electron menu bar to start the sync from scratch
- fixes db import
- fixes build ui script
**Depends** on these PRs:
- https://github.com/bitfinexcom/bfx-report/pull/174
- https://github.com/bitfinexcom/bfx-report-express/pull/9
- https://github.com/bitfinexcom/bfx-reports-framework/pull/87

New auth way

---

scripts/build-ui.sh
src/create-menu.js
src/initialize-app.js
src/trigger-electron-load.js

This PR fixes electron auth, sends an event into UI to fetch users data before sign-in when the backend is ready

Send event into ui before sign-in when backend is ready

---

package.json

This version fixes the login issue and filters by id.

Version 3.0.1

---

package.json

Bump version and sub modules for 3.2.0 release

Version 3.2.0

---

Dockerfile.win-builder

This PR fixes Wine GPG signature issue for Win Docker image, related to issues:
https://forum.winehq.org/viewtopic.php?f=8&t=32192#p121683
https://askubuntu.com/questions/1129025/invalid-signatures-expkeysig

Fix wine gpg signature issue for docker

---

scripts/build-ui.sh

This PR fixes UI build in the docker container

Fix UI build in docker container

---

package.json

This PR has the last sub modules used for this version.

Version 3.2.1

---

package.json
scripts/init.sh

This PR improves the UI build watchdog to allow watching the UI build has been completed in 30 minutes, if not successful than exit with an error

Improve UI build watchdog

---

package.json

version 3.3.1

---

src/auto-updater/index.js
src/error-manager/index.js

This PR adds the ability to launch electron app when internet disconnected
- https://github.com/bitfinexcom/bfx-reports-framework/pull/168

Add ability to launch electron app when internet disconnected

---

package.json

Bump version + update sub modules

Bump to version 3.5.0

---

scripts/init.sh

This PR adds the required `grc-slack` config for the launching app on the step when app is building
- https://github.com/bitfinexcom/bfx-reports-framework/pull/174

Add grc-slack config

---

package.json

Version 3.5.2

---

src/error-manager/index.js

This PR adds abililty to not open a new issue when can't download differentially, it would fallback to full download

Don't open a new issue when can't download differentially

---

package.json

This PR bumps electron version to 3.6.0

Bump to version 3.6.0

---

package.json

This PR has been created to update Beta to 1.6.2

Beta 1.6.2

---

package.json

version 3.6.3

---

CHANGELOG.md

This PR adds changelog for `v3.6.2` and `v3.6.3`

Add changelog for v3.6.2 and v3.6.3

---

docs/user-manual.md
index.js
package.json
scripts/node/generate-zipand-blockmap.js
src/change-loading-win-visibility-state.js
src/create-menu.js
src/enforce-macos-app-location.js
src/helpers/get-debug-info.js
src/helpers/index.js
src/helpers/manage-window.js
src/helpers/product-name.js
src/window-creators.js

This PR reworks the electron menu structure of the app. Base changes:
- Bumps `electron` version up to `13.6.9`
- Fixes focus/blur and show/hide states of windows to work properly with the menu bar
- Bumps `showdown` up to `2.0.3` to have the last bugfixes for MD rendering
- Bumps `github-markdown-css` up to `5.1.0` to have MD style fixes
- Fixes getting/setting product name to show proper menu item on Mac
- Reworks electron menu structure. The main point is to use the built-in `role` behavior to give the best native experience, check the description:
- https://www.electronjs.org/docs/latest/api/menu#examples
- https://www.electronjs.org/docs/latest/api/menu-item#roles
- Updates the corresponding sections of the user manual
Menu bar examples on Mac:
Menu bar examples on Linux (there …

Rework electron menu structure

---

CHANGELOG.md
package.json

This PR releases version 3.7.1. Changelog:
- Added option to quickly clear filters in the UI. PR: [bfx-report-ui#501](https://github.com/bitfinexcom/bfx-report-ui/pull/501)
- Added a link to affiliates dashboard on `Affiliates Earnings` page for better conversion and convenience in the UI. PR: [bfx-report-ui#512](https://github.com/bitfinexcom/bfx-report-ui/pull/512)
- Bumped UI dependency to have the last fixes. PRs: [bfx-report-ui#500](https://github.com/bitfinexcom/bfx-report-ui/pull/500), [bfx-report-ui#502](https://github.com/bitfinexcom/bfx-report-ui/pull/502), [bfx-report-ui#503](https://github.com/bitfinexcom/bfx-report-ui/pull/503), [bfx-report-ui#504](https://github.com/bitfinexcom/bfx-report-ui/pull/504), [bfx-report-ui#505](https://github.com/bitfinexcom/bfx-report-ui/pull/505) …

Release version 3.7.1 to beta

---

CHANGELOG.md
package.json

Version 3.7.2 change log:
- Adds Balance(USD) precision selector to the Wallets section. PR: [bfx-report-ui#522](https://github.com/bitfinexcom/bfx-report-ui/pull/522)
- Adds logic for merging similar trades, with the same orderId and execPrice, to the one dot on the Candles chart for better representation and readability in the UI. PR: [bfx-report-ui#515](https://github.com/bitfinexcom/bfx-report-ui/pull/515)
- Removes Input Timezone picker from Preferences and related logic for setting and using manually selected timezone for inputs. PR: [bfx-report-ui#521](https://github.com/bitfinexcom/bfx-report-ui/pull/521)
- Adds sub accounts selection persistence in Multiple Accounts login mode in the UI. PR: [bfx-report-ui#518](https://github.com/bitfinexcom/bfx-report-ui/pull/518)
- Fixed issues …

Push version 3.7.2 to Beta

---

CHANGELOG.md
package.json

- Go to a specific date on the candles chart [bfx-report-ui#527](https://github.com/bitfinexcom/bfx-report-ui/pull/527)
- Add order metadata to csv [bfx-report#264](https://github.com/bitfinexcom/bfx-report/pull/264) and [bfx-report-framework#226](https://github.com/bitfinexcom/bfx-report-framework/pull/226)
- Changes is calendar. Picked timezone its also used in the calendar [bfx-report-ui#529](https://github.com/bitfinexcom/bfx-report-ui/pull/529)
- Charts prices representation now has thousands separator [bfx-report-ui#523](https://github.com/bitfinexcom/bfx-report-ui/pull/523)
- Increase limit in candles sync for speed improment [bfx-report#262](https://github.com/bitfinexcom/bfx-report/pull/262) and [bfx-report-framework#224](https://github.com/bitfinexcom/bfx-report-framework/pull/22 …

Bump beta to version 3.7.3

---

CHANGELOG.md
package.json

- Added ability to persist columns adjustments. PR: [bfx-report-ui#530](https://github.com/bitfinexcom/bfx-report-ui/pull/530)
- Implemented selectable charts area and `Sum Up` range values feature for the `Traded Volume` and `Fees` reports. PR: [bfx-report-ui#535](https://github.com/bitfinexcom/bfx-report-ui/pull/535)
- Added `FUSE` technology description for `AppImage` into the documentation section
- Added notification sync is being paused until connection is resumed. PRs: [bfx-report#266](https://github.com/bitfinexcom/bfx-report/pull/266), [bfx-reports-framework#230](https://github.com/bitfinexcom/bfx-reports-framework/pull/230), [bfx-report-ui#537](https://github.com/bitfinexcom/bfx-report-ui/pull/537)
- Rounded `Account Summary` displayed values for better representation …

Release version 3.7.4 to beta

---

scripts/build-ui.sh

This PR fixes url to get api keys to [www.bitfinex.com](http://www.bitfinex.com/)

Fix url to get api keys

---

CHANGELOG.md
package.json

- Added `ENET` errors for reconnection when fetching data from the `BFX api_v2`. PR: [bfx-report#273](https://github.com/bitfinexcom/bfx-report/pull/273)
- Added ability to use the `inner max` request limit to the `BFX api_v2` to seed up syncing data. PR: [bfx-report#274](https://github.com/bitfinexcom/bfx-report/pull/274)
- Added ability to display minimum derivative fees between sub-accounts. PR: [bfx-reports-framework#241](https://github.com/bitfinexcom/bfx-reports-framework/pull/241)
- Added ability to turn off the auto-update while building releases using the env var `IS_AUTO_UPDATE_DISABLED=1` or the popup of GitHub Actions for `beta` releases [bfx-report-electron#170](https://github.com/bitfinexcom/bfx-report-electron/pull/170)
- Added reports for Turkey. PR: …

Release version 4.0.0 to beta

---

.github/workflows/build-electron-app.yml
CHANGELOG.md
package.json

- Added `BFX` auth token support to the backend of the framework mode. PRs: [bfx-report#281](https://github.com/bitfinexcom/bfx-report/pull/281), [bfx-reports-framework#256](https://github.com/bitfinexcom/bfx-reports-framework/pull/256)
- Added ability to send `emitCsvGenerationCompletedToOne` event by the WS when CSV reports generation is finished in the background queue, only for the framework mode. In the UI we will show a spinner on the export btn and the corresponding popup at an appropriate time after finishing generation (in some cases it can take a lot of time). PRs: [bfx-report#282](https://github.com/bitfinexcom/bfx-report/pull/282), [bfx-reports-framework#257](https://github.com/bitfinexcom/bfx-reports-framework/pull/257)
- Restructures `Reports` main navigation using …

Release version 4.3.0

---

CHANGELOG.md
package.json

- Added `symbol` field to the `currencies` model in order to have the same payload as from the `bfx-report`. PR: [bfx-reports-framework#278](https://github.com/bitfinexcom/bfx-reports-framework/pull/278)
- Bumped ElectronJS version up to `v21.3.3` to have NodeJS `v16` under the hood to resolve the ability to build UI and ElectronJS releases using the same NodeJS version. PRs: [bfx-report-electron#201](https://github.com/bitfinexcom/bfx-report-electron/pull/201), [bfx-report-ui#640](https://github.com/bitfinexcom/bfx-report-ui/pull/640), [bfx-facs-db-better-sqlite#5](https://github.com/bitfinexcom/bfx-facs-db-better-sqlite/pull/5)
- Resolved deprecation warning `fs.rmdir` for the `bfx-reports-framework` due to migration NodeJS to `v16`. PR: …

Release version 4.6.0 to beta

---

CHANGELOG.md
package.json

- Added a note to the electron app that `BFX API Staging` is used. PR: [bfx-report-electron#207](https://github.com/bitfinexcom/bfx-report-electron/pull/207)
- Added app download section available for the web users and corresponding logic where they can get the latest `Reports App` version for their OS. PR: [bfx-report-ui#657](https://github.com/bitfinexcom/bfx-report-ui/pull/657)
- Implemented displaying accounts group name (if available) for multiple accounts instead of the primary account email on the main `Sign In` screen for better clearance to the users. Implemented the possibility of changing existing accounts groups names for multiple accounts. PR: [bfx-report-ui#659](https://github.com/bitfinexcom/bfx-report-ui/pull/659)
- Increased `getAccountSummary` request timeout to `30s`, …

Release version 4.7.1 to beta

---

.github/workflows/build-electron-app.yml

This PR removes `Cache Docker images` GH Actions step

Remove Cache Docker images GH Actions step

---

CHANGELOG.md
package.json

- Added currency lists for platform consistency. PRs: [bfx-report#323](https://github.com/bitfinexcom/bfx-report/pull/323), [bfx-reports-framework#310](https://github.com/bitfinexcom/bfx-reports-framework/pull/310), [bfx-report-ui#688](https://github.com/bitfinexcom/bfx-report-ui/pull/688)
- Added support to DB migration for `temp` tables, `temp` tables will be removed for the non-completed sync if DB schema is changed. PR: [bfx-reports-framework#311](https://github.com/bitfinexcom/bfx-reports-framework/pull/311)
- Added ability to overwrite `RPC` timeout to have `httpRpcTimeout` and `wsRpcTimeout` options that can be overwritten in the electron environment to `10mins` for complicated reports which can have a lot of internal calls to the `BFX API` that can take significant time. It fixed …

Release version 4.10.0 to staging

---

.github/workflows/ci.yml
.github/workflows/test-report.yml

This PR adds test runner and report workflows to GitHub actions
---
Report examples of tests:
- https://github.com/ZIMkaRU/bfx-report-electron/runs/17562569768
- https://github.com/ZIMkaRU/bfx-report-electron/actions/runs/6469125870

Add test runner and report to GitHub actions

---

CHANGELOG.md
package.json

- Added test runner and report to the `GitHub Actions` of the `bfx-facs-db-better-sqlite` repo. PR: [bfx-facs-db-better-sqlite#8](https://github.com/bitfinexcom/bfx-facs-db-better-sqlite/pull/8)
- Added an endpoint to get the `summary by asset` (for 30 day period) for the new summary page of the framework mode. PR: [bfx-reports-framework#330](https://github.com/bitfinexcom/bfx-reports-framework/pull/330)
- Implemented currency name representation depending on the transport layer used for the `Tether` transactions in the `Movements` report. PR: [bfx-report-ui#721](https://github.com/bitfinexcom/bfx-report-ui/pull/721)
- Implemented the possibility of submitting `username/password` and `OTP` via the `Enter` button during the `2FA` sign-up flow. PR: …

Release version 4.14.0 to staging

---

src/auto-updater/index.js

This PR fixes 11 auto-update-toast:width listeners added
---
Bug report is taken here from the beta release:
- https://github.com/ZIMkaRU/bfx-report-electron/issues/24

Fix 11 auto-update-toast:width listeners added

---

CHANGELOG.md
package.json

- Added missing translations for `2FA`. PR: [bfx-report-ui#774](https://github.com/bitfinexcom/bfx-report-ui/pull/774)
- Implemented exporting to PDF support for `Ledgers` and `Tax Reports`. PRs: [bfx-report#347](https://github.com/bitfinexcom/bfx-report/pull/347), [bfx-reports-framework#352](https://github.com/bitfinexcom/bfx-reports-framework/pull/352), [bfx-report-electron#319](https://github.com/bitfinexcom/bfx-report-electron/pull/319), [bfx-ext-pdf-js#4](https://github.com/bitfinexcom/bfx-ext-pdf-js/pull/4), [bfx-report#349](https://github.com/bitfinexcom/bfx-report/pull/349), [bfx-reports-framework#354](https://github.com/bitfinexcom/bfx-reports-framework/pull/354), [bfx-report-ui#775](https://github.com/bitfinexcom/bfx-report-ui/pull/775)
- Added detection for `BFX` auth error: …

Release version 4.20.0 to staging

---

CHANGELOG.md
package.json

- Added ability to handle `PDFBufferUnderElectronCreationError` error to use WebSockets to inform users for better UX. PRs: [bfx-report#354](https://github.com/bitfinexcom/bfx-report/pull/354), [bfx-reports-framework#359](https://github.com/bitfinexcom/bfx-reports-framework/pull/359)
- Implemented support for `emitReportFileGenerationFailedToOne` ws events on UI side to inform users about report generation failing. PR: [bfx-report-ui#787](https://github.com/bitfinexcom/bfx-report-ui/pull/787)
- Added missing translations for PDF reports. PRs: [bfx-report#356](https://github.com/bitfinexcom/bfx-report/pull/356), [bfx-reports-framework#362](https://github.com/bitfinexcom/bfx-reports-framework/pull/362)
- Added DB migration for `publicCollsConf` table name with Cyrillic `c`. PR: …

Release version 4.21.0 to staging

---

.github/workflows/ci.yml

This PR adds `3` retries for the test run before it fails

Add several retries for the test run before it fails

---

CHANGELOG.md
package.json

- Added `3` retries for the test run before it fails, increased timeouts for mocha hooks. PRs: [bfx-report#368](https://github.com/bitfinexcom/bfx-report/pull/368), [bfx-report-electron#374](https://github.com/bitfinexcom/bfx-report-electron/pull/374), [bfx-reports-framework#372](https://github.com/bitfinexcom/bfx-reports-framework/pull/372), [bfx-reports-framework#374](https://github.com/bitfinexcom/bfx-reports-framework/pull/374)
- Implemented the possibility to `Reset Column Widths` via the context menu (right click) on column headers. PR: [bfx-report-ui#808](https://github.com/bitfinexcom/bfx-report-ui/pull/808)
- Implemented the possibility to customize (1-7 days range supported) authorization token TTL via the `Preferences` menu in the app. PR: …

Release version 4.24.0 to staging

---

src/auto-updater/index.js
src/change-sync-frequency.js
src/error-manager/show-modal-dialog.js
src/show-docs/index.js

This PR fixes loading ui fonts to all modal windows

Fix loading ui fonts to all modal windows

---

build/locales/en/translations.json
build/locales/ru/translations.json
src/change-sync-frequency.js

This PR adds translation support to the `change-sync-frequency` module
---

Add translation support to change-sync-frequency module

---

CHANGELOG.md
package.json

- Implemented `Your Assets` section for the web `Account Summary` page. Improved sections titles styling. PR: [bfx-report-ui#880](https://github.com/bitfinexcom/bfx-report-ui/pull/880)
- Implemented `UI` language selection binding with `ElectronJS` wrapper. PR: [bfx-report-ui#882](https://github.com/bitfinexcom/bfx-report-ui/pull/882)
- Extended ElectronJS app wrapper translations. Improved the app-init-error layout. Fixed logs collection for bug report. PR: [bfx-report-electron#422](https://github.com/bitfinexcom/bfx-report-electron/pull/422)
- Added translation support to the `error manager` module. PR: [bfx-report-electron#428](https://github.com/bitfinexcom/bfx-report-electron/pull/428)
- Added translation support to the `native notifications` module. PR: …

Release version 4.30.0 to staging

---

src/window-creators/index.js
src/window-creators/layouts/app-init.html
src/window-creators/main-renderer-ipc-bridge/general-ipc-channel-handlers.js
src/window-creators/main-renderer-ipc-bridge/preload.js

This PR adds a small typical `_` button (in the top right corner) to minimize the loading window
---
Examples:

Add button to minimize loading window

---

.eslintrc
scripts/build-ui.sh

This PR fixes the UI setup flow for the dev mode
---
Basic changes:
- Prevent throwing error if no eslint config from previous ui build
- Use eslint config in the root only for electron part

Fix ui setup flow for dev mode

---

electronEnv.json.example

This PR disables native title menu bar to use UI implementation via electron renderer ipc bridge
---
- https://github.com/bitfinexcom/bfx-report-ui/pull/898

Disable native title menu bar

---

CHANGELOG.md
package.json

- Implemented `Electron` app menu bar and corresponding functionality in the UI title instead of the native one. This is very useful as it saves overall space and at the same time constantly displays the menu and does not require the user to press the `Alt` key to display it (as the practice has shown, because of the last one, many inexperienced users do not even know about the existence of menu functions). Available for the `Windows` and `Linux` app users. On the `Mac` we have to hide the menu in the UI and show the native electron menu bar due to some `MacOS` specifics, it's impossible to have proper menu item control from the UI. PR: [bfx-report-ui#898](https://github.com/bitfinexcom/bfx-report-ui/pull/898)
- Added exponential backoff and jitter for bfx-api requests to improve `Rate …

Release version 4.33.0 to staging

---

package.json

This PR updates deps with vulnerabilities

Update deps with vulnerabilities

---

build/locales/es-EM/translations.json
build/locales/pt-BR/translations.json
build/locales/tr/translations.json
build/locales/vi/translations.json
build/locales/zh-CN/translations.json
build/locales/zh-TW/translations.json

This PR adds the rest of the translation files:
- es-EM
- pt-BR
- tr
- vi
- zh-CN
- zh-TW

Add rest of translation files

---

.gitignore
.npmrc
package-lock.json

This PR adds `package-lock` file based on the last changes in the `staging` branch due to the last security requirements

Add package-lock file

---

CHANGELOG.md
package.json

- Added `light/dark` themes to the electron wrapper and adds ability to couple with the UI. PR: [bfx-report-electron#511](https://github.com/bitfinexcom/bfx-report-electron/pull/511)
- Added the rest of translation files to the electron wrapper. PR: [bfx-report-electron#517](https://github.com/bitfinexcom/bfx-report-electron/pull/517)
- Added ability to display `Login to Reports with token` screen after the logout (like it was before the previous updates) and removed the outdated title from it. Implemented logging out from the main platform on `Reports` logout. PR: [bfx-report-ui#902](https://github.com/bitfinexcom/bfx-report-ui/pull/902)
- Increased `WebSockets` ping interval between `HTTP` server and `Grenache` worker for performance due to heavy sync cases. PR: …

Release version 4.34.0 to staging

---

CHANGELOG.md
package-lock.json
package.json

- Added ability to avoid queuing sync by scheduler if sync is already in progress to prevent redundant sync in case a user has lots of data and sync takes time until the run of the scheduler. PR: [bfx-reports-framework#446](https://github.com/bitfinexcom/bfx-reports-framework/pull/446)
- Added `Margin trading` and `Derivative` support to the `Tax Report` sources. PR: [bfx-report-ui#909](https://github.com/bitfinexcom/bfx-report-ui/pull/909)
- Changed the order of getting the price of the pub trades moving from the end to the start by timestamps to overcome some rare cases. Related to this issue: [bfx-report-electron#493](https://github.com/bitfinexcom/bfx-report-electron/issues/493). PR: [bfx-reports-framework#445](https://github.com/bitfinexcom/bfx-reports-framework/pull/445)
- Disabled …

Release version 4.34.1 to staging

---

CHANGELOG.md
package-lock.json
package.json

- Added warning message styles for PDF reports. PR: [bfx-report#429](https://github.com/bitfinexcom/bfx-report/pull/429)
- Added ability to continue the `Tax Report` generation without `delisted` currencies. PR: [bfx-reports-framework#449](https://github.com/bitfinexcom/bfx-reports-framework/pull/449)
- Added ability to deduct trading fees in the `Tax Report`. Added a flag `shouldFeesBeDeducted` to use that via a checkbox in the UI. PR: [bfx-reports-framework#450](https://github.com/bitfinexcom/bfx-reports-framework/pull/450)
- Added native behavior to minimize and close the loading window. The main reason is to provide the ability to `minimize` and then `restore` the loading window on all OSs as each OS has a specific behavior. Also added a close button to be able to interrupt the app …

Release version 4.35.0 to staging

---

.npmrc

Reverts bitfinexcom/bfx-report-electron#549

Revert "update .npmrc"

---

CHANGELOG.md
package-lock.json
package.json

- Implemented `USDT0ARB`, `USDT0INK` and `USDT0OPX` support in the symbols filters. PR: [bfx-report-ui#958](https://github.com/bitfinexcom/bfx-report-ui/pull/958)
- Added network to `Tether` ccy for movement export similar to the UI representation. Added a similar approach as on the UI side. PR: [bfx-report#446](https://github.com/bitfinexcom/bfx-report/pull/446)
- Showed `mtsStarted` instead of `mtsUpdated` timestamp in the `Date` column of the `Movements` report. PR: [bfx-report-ui#960](https://github.com/bitfinexcom/bfx-report-ui/pull/960)
- Added `created` and `updated` timestamp for movements export. PR: [bfx-report#448](https://github.com/bitfinexcom/bfx-report/pull/448)
- Reworked and optimized `WalletSelector` in a more performant way. PR: …

Release version 4.37.0 to staging
